import type { EffectKind, EffectPreset } from './types';
import type { GestureKind } from '../vision/types';

export const EFFECT_PRESETS: EffectPreset[] = [
  {
    id: 'seal',
    gesture: 'palms_joined',
    name: '灵印阵',
    description: '在双手之间展开定位印环。',
    element: 'qi',
    palette: { core: '#fff6e6', mid: '#45ddff', rim: '#166f9c', spark: '#ffd479', glow: '#34c8ff' },
    color: '#45ddff',
    accent: '#ffd479',
    intensity: 0.86,
    durationMs: 1500,
  },
  {
    id: 'shockwave',
    gesture: 'push_palm',
    name: '冲击波',
    description: '从掌心沿推掌方向扩散。',
    element: 'qi',
    palette: { core: '#f2feff', mid: '#45e0ff', rim: '#1390c4', spark: '#b6f7ff', glow: '#37c8ff' },
    color: '#45e0ff',
    accent: '#b6f7ff',
    intensity: 0.92,
    durationMs: 1250,
  },
  {
    id: 'energy_orb',
    gesture: 'charge_stance',
    name: '能量球',
    description: '在双手之间凝聚能量核。',
    element: 'qi',
    palette: { core: '#ffffff', mid: '#7c5cff', rim: '#3a1fb0', spark: '#c7b6ff', glow: '#6a4cff' },
    color: '#7c5cff',
    accent: '#c7b6ff',
    intensity: 1,
    durationMs: 1700,
  },
  {
    id: 'speed_lines',
    gesture: 'punch',
    name: '拳风',
    description: '沿手臂方向切出短促拳风。',
    element: 'qi',
    palette: { core: '#ffffff', mid: '#cfeaff', rim: '#6fa8d6', spark: '#ffffff', glow: '#9fd0ff' },
    color: '#cfeaff',
    accent: '#ffffff',
    intensity: 0.74,
    durationMs: 900,
  },
  {
    id: 'light_column',
    gesture: 'raised_hand',
    name: '光柱',
    description: '在举起的手附近落下光束。',
    element: 'gold',
    palette: { core: '#fffaf0', mid: '#ffd66b', rim: '#c98a26', spark: '#fff1c2', glow: '#ffc04d' },
    color: '#ffd66b',
    accent: '#fff1c2',
    intensity: 0.82,
    durationMs: 1350,
  },
  {
    id: 'aura_burst',
    gesture: 'crouch',
    name: '爆气',
    description: '从身体下方扩散地面气浪。',
    element: 'fire',
    palette: { core: '#fff3e0', mid: '#ff7a3c', rim: '#b8330f', spark: '#ffd08a', glow: '#ff5a2c' },
    color: '#ff7a3c',
    accent: '#ffd08a',
    intensity: 0.96,
    durationMs: 1200,
  },
  {
    id: 'barrier',
    gesture: 'cross_guard',
    name: '护盾展开',
    description: '交叉手臂前方展开防御场。',
    element: 'gold',
    palette: { core: '#fff7e6', mid: '#ffb347', rim: '#c9791f', spark: '#ffe0a3', glow: '#ffae3a' },
    color: '#ffb347',
    accent: '#ffe0a3',
    intensity: 0.9,
    durationMs: 1450,
  },
  {
    id: 'skyfall',
    gesture: 'both_hands_raised',
    name: '天幕落光',
    description: '双手上举后落下多束能量光。',
    element: 'ice',
    palette: { core: '#ffffff', mid: '#aee0ff', rim: '#5b9fd6', spark: '#e6f6ff', glow: '#8fcaff' },
    color: '#aee0ff',
    accent: '#e6f6ff',
    intensity: 0.95,
    durationMs: 1500,
  },
  {
    id: 'guard_flare',
    gesture: 'guard_stance',
    name: '斗气护身',
    description: '拳架周围形成短促气焰。',
    element: 'wood',
    palette: { core: '#fbffe8', mid: '#aef06a', rim: '#5a9a1f', spark: '#e4ffb0', glow: '#8fe04a' },
    color: '#aef06a',
    accent: '#e4ffb0',
    intensity: 0.78,
    durationMs: 1200,
  },
  {
    id: 'beam',
    gesture: 'finger_point',
    name: '指令射线',
    description: '从指尖射出集束光线。',
    element: 'lightning',
    palette: { core: '#ffffff', mid: '#67efff', rim: '#1f9fc4', spark: '#d6fbff', glow: '#45dcff' },
    color: '#67efff',
    accent: '#d6fbff',
    intensity: 0.86,
    durationMs: 900,
  },
  {
    id: 'slash',
    gesture: 'side_slash',
    name: '横扫斩击',
    description: '跟随手臂横扫切出弧光。',
    element: 'blade',
    palette: { core: '#fffaf3', mid: '#ff5d6e', rim: '#b8202f', spark: '#ffd0d6', glow: '#ff4055' },
    color: '#ff5d6e',
    accent: '#ffd0d6',
    intensity: 0.92,
    durationMs: 920,
  },
];

export const JUMP_PRESET: EffectPreset = {
  id: 'aura_burst',
  gesture: 'jump',
  name: '空跃爆气',
  description: '跳跃瞬间在落点附近扩散气浪。',
  element: 'qi',
  palette: { core: '#ffffff', mid: '#b7f9ff', rim: '#5aa6c4', spark: '#ffffff', glow: '#8fe6ff' },
  color: '#b7f9ff',
  accent: '#ffffff',
  intensity: 0.8,
  durationMs: 950,
};

export function presetForGesture(gesture: GestureKind): EffectPreset {
  if (gesture === 'jump') {
    return JUMP_PRESET;
  }

  return EFFECT_PRESETS.find((preset) => preset.gesture === gesture) ?? EFFECT_PRESETS[0];
}

export function presetById(id: EffectKind): EffectPreset {
  return EFFECT_PRESETS.find((preset) => preset.id === id) ?? EFFECT_PRESETS[0];
}
